fix compile error with latest gst headers
A conflict between XDM and gst headers results in:

  cc1: warnings being treated as errors
  In file included from gstducati.h:32,
                   from gstducatividdec.h:25,
                   from gstducativp7dec.h:25,
                   from gstducativp7dec.c:40:
  /usr/include/dce/xdc/std.h:172: error: "restrict" redefined
  /usr/include/gstreamer-0.10/gst/gstmacros.h:44: note: this is the location of the previous definition

The solution is to ensure XDM headers are included first.